// Nigerian banks (name + CBN/NIP code). Used as the fallback/mock bank list.
// In live mode the authoritative list comes from the rail (Squad /payout/banks),
// which supersedes this — so codes here only need to be reasonable for sandbox.
export type NgBank = { name: string; code: string };

export const NIGERIA_BANKS: NgBank[] = [
  { name: "Access Bank", code: "044" },
  { name: "Access Bank (Diamond)", code: "063" },
  { name: "Citibank Nigeria", code: "023" },
  { name: "Ecobank Nigeria", code: "050" },
  { name: "Fidelity Bank", code: "070" },
  { name: "First Bank of Nigeria", code: "011" },
  { name: "First City Monument Bank (FCMB)", code: "214" },
  { name: "Globus Bank", code: "00103" },
  { name: "Guaranty Trust Bank (GTBank)", code: "058" },
  { name: "Heritage Bank", code: "030" },
  { name: "Jaiz Bank", code: "301" },
  { name: "Keystone Bank", code: "082" },
  { name: "Lotus Bank", code: "303" },
  { name: "Optimus Bank", code: "107" },
  { name: "Parallex Bank", code: "104" },
  { name: "Polaris Bank", code: "076" },
  { name: "PremiumTrust Bank", code: "105" },
  { name: "Providus Bank", code: "101" },
  { name: "Signature Bank", code: "106" },
  { name: "Stanbic IBTC Bank", code: "221" },
  { name: "Standard Chartered Bank", code: "068" },
  { name: "Sterling Bank", code: "232" },
  { name: "SunTrust Bank", code: "100" },
  { name: "TAJ Bank", code: "302" },
  { name: "Titan Trust Bank", code: "102" },
  { name: "Union Bank of Nigeria", code: "032" },
  { name: "United Bank for Africa (UBA)", code: "033" },
  { name: "Unity Bank", code: "215" },
  { name: "Wema Bank (ALAT)", code: "035" },
  { name: "Zenith Bank", code: "057" },
  // Merchant / non-interest / others
  { name: "Coronation Merchant Bank", code: "559" },
  { name: "FBNQuest Merchant Bank", code: "060" },
  { name: "FSDH Merchant Bank", code: "501" },
  { name: "Greenwich Merchant Bank", code: "562" },
  { name: "Rand Merchant Bank", code: "502" },
  // Fintech / MFBs (popular)
  { name: "Kuda Microfinance Bank", code: "50211" },
  { name: "OPay (Paycom)", code: "999992" },
  { name: "PalmPay", code: "999991" },
  { name: "Moniepoint MFB", code: "50515" },
  { name: "Carbon (One Finance)", code: "565" },
  { name: "Sparkle Microfinance Bank", code: "51310" },
  { name: "VFD Microfinance Bank", code: "566" },
  { name: "Rubies MFB", code: "125" },
  { name: "Mint MFB", code: "50304" },
  { name: "Eyowo", code: "50126" },
  { name: "FairMoney MFB", code: "51318" },
  { name: "Fortis Microfinance Bank", code: "501" },
  { name: "Hackman Microfinance Bank", code: "51251" },
  { name: "Ibile Microfinance Bank", code: "51244" },
  { name: "Lagos Building Investment Company (LBIC)", code: "90052" },
  { name: "Mkudi", code: "50224" },
  { name: "Paga", code: "100002" },
  { name: "Parkway (ReadyCash)", code: "311" },
  { name: "Page MFBank", code: "560" },
  { name: "TCF MFB", code: "51211" },
  { name: "AB Microfinance Bank", code: "50926" },
  { name: "Accion Microfinance Bank", code: "602" },
  { name: "Stanbic Mobile Money", code: "304" },
];
