#!/usr/bin/env bash
#
# Neflo server provisioning — run ONCE on neflo.torama.money.
#
#   - creates a no-login system user `neflo` that owns and runs the app
#   - lays out /opt/neflo (code + data) with correct, inheritable permissions
#   - lets `user1` manage deploys (group membership + scoped sudo)
#   - creates an isolated Docker network so Neflo can't touch other apps
#   - DETECTS FREE HOST PORTS before use and records them in /opt/neflo/.env.ports
#
# Run as user1 (NOT root):  ./scripts/server-setup.sh
# Re-running is safe (idempotent).
#
set -euo pipefail

APP_USER="neflo"
APP_GROUP="neflo"
ADMIN_USER="${ADMIN_USER:-user1}"
ROOT_DIR="/opt/neflo"
DOCKER_NET="neflo-net"

# Ports already taken by Otuburu / common services — never reuse these.
RESERVED_PORTS=(22 80 443 5432 8082 8083 8084 9090)
APP_PORT_START="${APP_PORT_START:-8090}"   # host port for the Next.js app (Apache proxies to it)

log() { printf '\033[1m%s\033[0m\n' "$*"; }

require_sudo() {
  if ! sudo -n true 2>/dev/null; then
    log "This script needs sudo. You may be prompted for your password."
    sudo true
  fi
}

# --- port helpers ---------------------------------------------------------
port_in_use() {
  # true if anything is listening on the given TCP port (incl. docker-proxy)
  if command -v ss >/dev/null 2>&1; then
    ss -Hltn "sport = :$1" 2>/dev/null | grep -q .
  else
    sudo lsof -iTCP:"$1" -sTCP:LISTEN -n -P 2>/dev/null | grep -q .
  fi
}

is_reserved() {
  local p="$1"
  for r in "${RESERVED_PORTS[@]}"; do [ "$p" = "$r" ] && return 0; done
  return 1
}

find_free_port() {
  local p="$1"
  while is_reserved "$p" || port_in_use "$p"; do
    p=$((p + 1))
  done
  echo "$p"
}

# -------------------------------------------------------------------------
main() {
  require_sudo

  log "==> 1/6  Create no-login app user '${APP_USER}'"
  if ! getent group "$APP_GROUP" >/dev/null; then
    sudo groupadd --system "$APP_GROUP"
  fi
  if ! id "$APP_USER" >/dev/null 2>&1; then
    sudo useradd --system --gid "$APP_GROUP" \
      --no-create-home --shell /usr/sbin/nologin "$APP_USER"
    echo "  created ${APP_USER}"
  else
    echo "  ${APP_USER} already exists"
  fi
  NEFLO_UID="$(id -u "$APP_USER")"
  NEFLO_GID="$(getent group "$APP_GROUP" | cut -d: -f3)"

  log "==> 2/6  Docker access"
  if ! command -v docker >/dev/null 2>&1; then
    echo "  ! Docker is not installed. Install Docker Engine + compose plugin, then re-run." >&2
    exit 1
  fi
  # user1 manages containers; app user does NOT need docker group (runs inside the container).
  if getent group docker >/dev/null && ! id -nG "$ADMIN_USER" | grep -qw docker; then
    sudo usermod -aG docker "$ADMIN_USER"
    echo "  added ${ADMIN_USER} to docker group (re-login to take effect)"
  fi

  log "==> 3/6  Directory layout under ${ROOT_DIR}"
  # Single Next.js monolith serves both frontend and backend; data dir holds
  # the Postgres volume + engine/app state so containers stay stateless.
  sudo mkdir -p "${ROOT_DIR}" "${ROOT_DIR}/app" "${ROOT_DIR}/data/postgres"
  sudo chown -R "${APP_USER}:${APP_GROUP}" "${ROOT_DIR}"
  # setgid so every new file/dir inherits the neflo group; group-writable for deploys.
  sudo find "${ROOT_DIR}" -type d -exec chmod 2775 {} +
  # data dir is owned by the app user only (Postgres/state) — keep it tight.
  sudo chmod 2770 "${ROOT_DIR}/data" "${ROOT_DIR}/data/postgres"

  log "==> 4/6  Let ${ADMIN_USER} write deploys into ${ROOT_DIR}"
  if ! id -nG "$ADMIN_USER" | grep -qw "$APP_GROUP"; then
    sudo usermod -aG "$APP_GROUP" "$ADMIN_USER"
    echo "  added ${ADMIN_USER} to ${APP_GROUP} group (re-login to take effect)"
  fi

  log "==> 4b/6  Scoped passwordless sudo for ${ADMIN_USER} (CI deploy)"
  # Lets the deploy workflow chown the app dir and reload Apache without a TTY.
  SUDOERS_FILE="/etc/sudoers.d/neflo-deploy"
  sudo tee "$SUDOERS_FILE" >/dev/null <<EOF
${ADMIN_USER} ALL=(root) NOPASSWD: /usr/bin/chown -R neflo\\:neflo /opt/neflo/app
${ADMIN_USER} ALL=(root) NOPASSWD: /usr/bin/chown -R neflo\\:neflo /opt/neflo
${ADMIN_USER} ALL=(root) NOPASSWD: /usr/bin/chown -R ${ADMIN_USER}\\:neflo /opt/neflo/app
${ADMIN_USER} ALL=(root) NOPASSWD: /usr/sbin/a2ensite neflo.torama.money
${ADMIN_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl reload apache2
EOF
  sudo chmod 0440 "$SUDOERS_FILE"
  sudo visudo -cf "$SUDOERS_FILE" >/dev/null && echo "  ${SUDOERS_FILE} valid"

  log "==> 5/6  Isolated Docker network '${DOCKER_NET}'"
  if ! docker network inspect "$DOCKER_NET" >/dev/null 2>&1; then
    docker network create "$DOCKER_NET" >/dev/null
    echo "  created ${DOCKER_NET}"
  else
    echo "  ${DOCKER_NET} already exists"
  fi

  log "==> 6/6  Detect free host port for the app"
  APP_PORT="$(find_free_port "$APP_PORT_START")"
  echo "  selected APP_PORT=${APP_PORT} (Postgres stays container-internal, no host port)"

  PORTS_FILE="${ROOT_DIR}/.env.ports"
  sudo tee "$PORTS_FILE" >/dev/null <<EOF
# Generated by server-setup.sh on $(date -u +%FT%TZ)
# Host port published for the Next.js app; Apache reverse-proxies to it.
APP_PORT=${APP_PORT}
# App user identity — the container runs as this uid:gid for volume permissions.
NEFLO_UID=${NEFLO_UID}
NEFLO_GID=${NEFLO_GID}
DOCKER_NET=${DOCKER_NET}
EOF
  sudo chown "${APP_USER}:${APP_GROUP}" "$PORTS_FILE"
  sudo chmod 0640 "$PORTS_FILE"

  cat <<SUMMARY

------------------------------------------------------------------
 Neflo server is provisioned.
   App user ........ ${APP_USER} (uid ${NEFLO_UID}, nologin)
   Code root ....... ${ROOT_DIR}/app   (deploy your repo here)
   Data root ....... ${ROOT_DIR}/data  (Postgres volume, ${APP_USER}-only)
   Docker network .. ${DOCKER_NET}
   App host port ... ${APP_PORT}   -> see ${ROOT_DIR}/.env.ports
   Apache .......... proxy neflo.torama.money -> http://127.0.0.1:${APP_PORT}

 Next:
   1) Log out/in once so ${ADMIN_USER}'s new groups apply.
   2) Copy the repo into ${ROOT_DIR}/app and add ${ROOT_DIR}/app/.env
   3) cd ${ROOT_DIR}/app && docker compose --env-file ../.env.ports up -d --build
------------------------------------------------------------------
SUMMARY
}

main "$@"
